{% set version = "2.0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bedmatrix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BEDMatrix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BEDMatrix/BEDMatrix_{{ version }}.tar.gz
  sha256: 53944ba9290d57525fd75751f575a882edc432183495bed15e5476499e82b337

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crochet >=2.3.0
  run:
    - r-base
    - r-crochet >=2.3.0

test:
  commands:
    - $R -e "library('BEDMatrix')"           # [not win]
    - "\"%R%\" -e \"library('BEDMatrix')\""  # [win]

about:
  home: https://github.com/QuantGen/BEDMatrix
  license: MIT
  summary: A matrix-like data structure that allows for efficient, convenient, and scalable subsetting of binary genotype/phenotype files generated by PLINK (<https://www.cog-genomics.org/plink2>), the whole genome association analysis toolset, without loading the entire file into memory.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: BEDMatrix
# Version: 2.0.3
# License: MIT + file LICENSE
# Title: Extract Genotypes from a PLINK .bed File
# Description: A matrix-like data structure that allows for efficient, convenient, and scalable subsetting of binary genotype/phenotype files generated by PLINK (<https://www.cog-genomics.org/plink2>), the whole genome association analysis toolset, without loading the entire file into memory.
# Authors@R: c( person("Alexander", "Grueneberg", email = "cran@agrueneberg.info", role = c("aut", "cre")), person("Gustavo", "de los Campos", email = "gustavoc@msu.edu", role = c("ctb")))
# URL: https://github.com/QuantGen/BEDMatrix
# BugReports: https://github.com/QuantGen/BEDMatrix/issues
# Depends: R (>= 3.0.2)
# Imports: methods, crochet (>= 2.3.0)
# Suggests: data.table, LinkedMatrix, tinytest
# NeedsCompilation: yes
# Packaged: 2020-07-07 20:47:13 UTC; agrueneberg
# Author: Alexander Grueneberg [aut, cre], Gustavo de los Campos [ctb]
# Maintainer: Alexander Grueneberg <cran@agrueneberg.info>
# Repository: CRAN
# Date/Publication: 2020-07-08 06:20:38 UTC
